# -*- coding: utf-8 -*-
"""Mustafa Karimi - (HW)In Class Activity 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o_S8bA2L9_6laV0p8Ujy_BWhi2QFM7mv

1) Create a Python program with a function called display_info. Inside this function, print
information about your favorite book, including its title, author, and a brief description. Call the
display_info function to showcase the details of your favorite book.
"""

def display_info():
    book = "Harry Potter"
    author = "J.K Rowling"
    description = "Harry Potter is a series of seven fantasy novels. It is about a young wizard and his friends who are all students at Hogwarts schools."
    print("My favorite book is", book)
    print("The books author is", author)
    print(description)

# Call the display_info so the code can be written
display_info()

"""2) Write Python functions to showcase the top attractions for the following travel
destinations: London, Paris, and New York. Each function should print the top
attractions for the respective destination.
"""

def london_attractions():
    print("\nHere are some popular destinations of London:")
    print("-Tower of London")
    print("-Buckingham Palace")
    print("-British Museum")

def paris_attractions():
    print("\nHere are some popular destinations of Paris:")
    print("-Eiffel Tower")
    print("-Louvre Museum")
    print("-Palace of Versailles")

def newyork_attractions():
    print("\nHere are some popular destinations of New York:")
    print("-Statue of Liberty")
    print("-Times Square")
    print("-Niagra Falls")

london_attractions()
paris_attractions()
newyork_attractions()

!pip3 install ColabTurtle
from ColabTurtle.Turtle import *

"""3) Write a Python program that uses the turtle graphics library to create a function named
draw_square. The function should draw a square using the turtle graphics module. The side
length of the square should be fixed within the function.
After defining the draw_square function, use it in your program to draw three squares. Ensure
that the squares do not overlap, and use appropriate turtle graphics commands to reset the
turtle's position between each square.
"""

import ColabTurtle.Turtle as turtle
turtle.initializeTurtle()

def draw_square(side_length):
    for i in range(4):
        turtle.forward(side_length)
        turtle.right(90)
draw_square(100)

turtle.penup()
turtle.forward(120)
turtle.pendown()

draw_square(100)

turtle.penup()
turtle.back(240)
turtle.pendown()

draw_square(100)

"""4) Write a Python function called find_even_numbers() that uses a for loop to find and print a list
of even numbers between 0 and 10.
"""

def find_even_numbers():
    even_numbers = []
    for number in range(0, 11):  # Include 10
        if number % 2 == 0:
            even_numbers.append(number)
    print("Even numbers between 0 and 10:", even_numbers)

# Call the function to see the output
find_even_numbers()