# -*- coding: utf-8 -*-
"""Mustafa Karimi - In Class Activity 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11bhtz57HqbwrY6nhUCrN6YMQhMqYkECT

1) We have a triangle, and we want to calculate its area. First, assign the length of the
base of the triangle to the variable name base, and assign the height of the triangle to
the variable name height. Using the assigned values of base and height, calculate the
area of the triangle and display it on the screen. The triangle we want to calculate the
area for has a base length of 10 cm and a height of 4 cm.
"""

base = 10
height = 4
area_of_triangle = (base * height) / 2
print('Area is:', area_of_triangle)

"""2) Suppose you have a vegetable garden that is 50cm in length and 80cm in width. If you
want to enclose the entire garden with a fence, and each fence length is 15cm, how
many fences would you need to cover the whole garden?
Write a new Python script to solve this problem. Begin with defining variables
fenceLength and gardenPerimeter, and then create a statement that calculates
how many fences would be needed. Finally, print the final result.

"""

fenceLength = 15
gardenPerimeter = 2 * (50 + 80)
numberOfFences = gardenPerimeter / fenceLength
print(numberOfFences)

"""3) Write a Python script to calculate the number of quarters, dimes, and dollars required
to represent 835 cents.
Your task is to create a Python program that takes the total amount in cents (835 cents
in this case) and converts it into the equivalent number of quarters, dimes, and dollars.
Utilize integer division (//) and the remainder operator (%) for this calculation.
For instance, when given 835 cents, the program should output something like:
Total Amount: 835 cents
Quarters: 1
Dimes: 1
Dollars: 8
You can just show number of cents after quarters, dimes and dollars, don’t need to do
nickels and pennies (you can if you want, it is the same logic
"""

# Total amount in cents
total_cents = 835

# Calulate the number of dollars
dollars = total_cents // 100
remaining_cents = total_cents % 100

# Calculate the number of quarters
quarters = remaining_cents // 25
remaining_cents = remaining_cents % 25

# Calculate the number of dimes
dimes = remaining_cents // 10
remaining_cents = remaining_cents % 10

# Print the amounts of each
print("Total Amount:", total_cents, "cents")
print("Quarters:", quarters)
print("Dimes:", dimes)
print("Dollars:", dollars)

"""4) Write a Python program that prints the following pattern using escape characters:
One
Two
Three
"""

print('One')
print('\tTwo')
print('\t\tThree')

"""5) Write a Python program that asks the user for their name and prints the following
message using escape characters:
"John" is a common name.
"""

name = input('Enter your name: ')
print(f'\"{name}\" is a common name.')

"""6) Write a Python program that defines a file path using escape characters and prints it:
C:\Users\Documents\MyFile.txt
"""

print('C:\\Users\\Documents\\MyFile.txt')