# -*- coding: utf-8 -*-
"""Mustafa Karimi - (HW)In Class Activity 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mh95r-0pc5m8kWwpwrTyaX_LTqNDo6Oe
"""

!pip3 install ColabTurtle
from ColabTurtle.Turtle import *

"""# 1) Create 8 sided octagon using turtle. Note that the angle of each point in a polygon is 45
degrees.
"""

import ColabTurtle.Turtle as turtle
turtle.initializeTurtle()

for _ in range(8):  # Repeat 8 times for 8 sides
    turtle.forward(100)
    turtle.left(45)  # Turn 45 degrees for each side

"""2) Make a turtle and set its color using the color method. Then write statements to have
the turtle trace a five-pointed star. This will require 5 copies of a move forward
followed by a turn. Note that the angle of each point in a five-pointed star is 36
degrees.
Then, add to your script a second turtle. Use the goto method to move the second
turtle to a new location (remembering that (0, 0) is the position where the turtles start).
Then have the second turtle draw another five-pointed star, in a different color just
after the first turtle has drawn its star.
"""

turtle.initializeTurtle()

turtle.color("red")
turtle.right(36)
turtle.forward(100)
turtle.right(108)
turtle.forward(100)
turtle.right(150)
turtle.forward(140)
turtle.right(155)
turtle.forward(140)
turtle.right(160)
turtle.forward(140)

turtle.goto(300, 200)

turtle.color("green")
turtle.right(36)
turtle.forward(100)
turtle.right(108)
turtle.forward(100)
turtle.right(150)
turtle.forward(140)
turtle.right(155)
turtle.forward(140)
turtle.right(160)
turtle.forward(140)

"""3) Create your own graphics using turtle."""

turtle.initializeTurtle()

turtle.color("pink")
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)

turtle.penup()
turtle.goto(200, 200)
turtle.pendown()

turtle.color("blue")
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)

turtle.penup()
turtle.goto(760,300)
turtle.pendown()
turtle.color("green")
for _ in range(8):
    turtle.forward(100)
    turtle.left(45)